name: Reusable Deploy
on: 
  workflow_call:
    inputs:
        artifact-name:
            description: Название файла развертывания
            required: false
            default: dist
            type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: Список файлов
              run: ls
            - name: Output information
              run: echo "Deploying & uploaging..."